### ISSUE TITLE
Spark on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [spark/core#54]
Howdy from The Changelog!

We'd love to get the Spark core team on the show sometime soon.

I'm guessing you've heard of the show, but if not -- The Changelog is a podcast covering what's fresh and new in open source. Listen to the show here http://thechangelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to talking to y'all!

Jerod, Managing Editor

**Comment by zsup** [comment]
Thanks Jerod! Would love to participate. Shoot me an email at zach at spark dot io and let's chat!
